### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by danielochuba** [diarisdiakite/To-do-list#4]
# Peer to peer code review
## You did a great job here, the UI is well-interactive. I would recommend that you makes some changes to this code.
- would look better if you Remove comments in the deleteTask.js file, to make it have only needed codes
- also I would suggest that you Try using the filter method to remove tasks.

**Comment by diarisdiakite** [comment]
Updated @danielochuba

**Comment by danielochuba** [comment]
@diarisdiakite weldone
